name: CI - Tests and Checks

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  # FIXME delete this job.
  test-ci:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: write
    steps:
      # +----------------------------------------------------------------------+
      # + Github Actions chores                                                +
      # +----------------------------------------------------------------------+

      - name: "Checkout code"
        uses: actions/checkout@v2

      - uses: cachix/install-nix-action@v27
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      # +----------------------------------------------------------------------+
      # + Dependency install                                                   +
      # +----------------------------------------------------------------------+

      - name: Install packages from Nix development environment
        run: nix develop --command true

      - name: Install Node dependencies
        run: nix develop --command -- pnpm install --frozen-lockfile

      # +----------------------------------------------------------------------+
      # + Tests and checks                                                     +
      # +----------------------------------------------------------------------+

      - name: Build flake package
        run: nix build .

      - name: Run tests
        run: nix develop --command -- pnpm run test

      - name: Run linter
        # Bun does not yet support ESlint.
        run: "nix develop --command -- pnpm run check:lint"

      - name: Check formatting
        run: "nix develop --command -- pnpm run check:format"
